{
  imports = [
    ./highlight-colors.nix
    ./lazy.nix
    ./lint.nix
    ./lualine.nix
    ./mini.nix
    ./neo-tree.nix
    ./neocord.nix
    ./nix.nix
    ./nui.nix
    ./snack.nix
    ./telescope.nix
    ./treesitter.nix
    ./visual-whitespace.nix
    ./web-devicons.nix
    ./twilight.nix
    ./toggleterm.nix
    ./cmp.nix
    ./transparent.nix
  ];
}
